using GB_seminar;

var homeWorkOne = new HomeWorkOne();
var seminarTwo = new Seminar2Online();
var homeworkTwo = new HomeWokrTwo();
var homeworkThree = new HomeWorkThree();
var homeworkFour = new HomeWorkFour();
var seminarFour = new Seminar4Online();
var seminarFive = new Seminar5Online();
var homeworkFive = new HomeWorkFive();
var seminarSix = new Seminar6Online();
var homeworkSix = new HomeworkSix();
var seminarSeven = new Seminar7Online();
var seminarEight = new Seminar8Online();
var homeworkSeven = new HomeWorkSeven();
var homeworkEight = new HomeWorkEight();

//homeworkTwo.TaskTen();
//homeworkTwo.TaskThirteen();
//homeworkTwo.TaskFifteen();
//seminarFour.Task30();
//homeworkFour.TaskTwentyNine();
//homeworkFour.TaskTwentyNineVer2();
//seminarFive.Task32();
//seminarFive.Task37();
//homeworkFive.TaskAdditional();
//seminarSix.Task44();
//homeworkSix.TaskAdditional();
//homeworkSix.TaskAdditionalV2();
//seminarEight.Task57();
//homeworkSeven.Task52();
homeworkEight.Task61();